- 
  name: Copying files to remote
  hosts: servers
  tasks:
  - name: Copy Files
    copy:
      src:
        /home/myfile.txt
      dest: /tmp/
      owner: pratik
      group: dev
      mode: ugo=rw #this will give all access to user, group, both etc
      backup: yes
