- 
  name: Install Package
  hosts: servers
  become: yes
  tasks:
  - name: Installing Nginx
    apt:
      name: nginx
      state: present
  - name: Starting the nginx service
    service:
      name: nginx
      state: started
      enabled: yes
