- 
  name: Modify Cron
  hosts: all
  tasks:
  - name: Remove Cron Job
    cron:
    name: Run test Script   #give the name of the task u want to remove
    state: absent
    user: pratik    #for a specific user
    job: /tmp/script/test.sh  #job is to run this script
    insertafter: PATH # if u want to execute particular script before or after previous script this keyword is used.
    disabled: yes       #if you want to stop running the script disabled is used
